### ISSUE TITLE
[SUGGESTION] Intel hardware-acceleration support

### ISSUE THREAD

**Issue by forart** [RainerMtb/cuvista#1]
Hi there, 1st of all thanks for your (volunteer) work.

Even if it would be great to have hardware-based acceleration for *all* platform, at the moment keep in consideration to add the Intel support could be a nice choice...

@intel's [oneAPI Samples](https://github.com/oneapi-src/oneAPI-samples) and/or [oneAPI Video Processing Library (oneVPL)](https://github.com/oneapi-src/oneVPL) gits may help.

Hope that inspires !

**Comment by RainerMtb** [comment]
At the moment I have no Intel gpu hardware to test against. If the project gains some interest I first want to look into accelerating the code as it is, I believe the cpu code can be improved quite a bit, and probably the cuda portion as well. I will think about other platforms

**Comment by RainerMtb** [comment]
I have included acceleration through OpenCL, although this probably needs more refinement, maybe some devices will produce garbage output, I will see.
