### ISSUE TITLE
Compiling on linux/ubuntu

### ISSUE THREAD

**Issue by abaldanz** [RainerMtb/cuvista#2]
Hello,

Thanks for your work, it's really brilliant.

Would you have a linux-compatible version or the Makelists.txt that can be used to compile your code on a linux machine?

Regards,

Axel

**Comment by RainerMtb** [comment]
Linux compatibility is on my list, I looked into it once but put it aside for the time. Some changes to the code are necessary besides the compilation process itself, and well, I dont know much about Linux at all. I will look into it.

**Comment by abaldanz** [comment]
Maybe you can help me if you've already done some work on it. I've written a CMakeLists.txt to compile the cpp and cuda code (removing all the GUI part which isn't useful to me and seems linked to Windows). 

`cmake_minimum_required(VERSION 3.12)
project(cuvista CUDA)

# Définir GCC comme compilateur pour C et C++
set(CMAKE_C_COMPILER "/usr/bin/gcc-13")
set(CMAKE_CXX_COMPILER "/usr/bin/g++-13")

# Définir GCC comme compilateur hôte pour CUDA
set(CUDA_HOST_COMPILER /usr/bin/g++-13)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CUDA_STANDARD 14)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)

# Inclure les répertoires d'en-tête
include_directories(include Matrix Deshaker CudaClasses)

# Définir les architectures CUDA
if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
  set(CMAKE_CUDA_ARCHITECTURES 75)
endif()

# Fichiers source C++ seulement
file(GLOB_RECURSE CPP_SOURCES "Matrix/*.cpp" "Deshaker/*.cpp" "cuvista/*.cpp")

# Fichiers source CUDA seulement
file(GLOB_RECURSE CUDA_SOURCES "CudaClasses/*.cu")

# Ajouter la bibliothèque CUDA
add_library(cuvista_cuda STATIC ${CUDA_SOURCES})
set_target_properties(cuvista_cuda PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
target_include_directories(cuvista_cuda PRIVATE ${CUDA_INCLUDE_DIRS})

# Créer l'exécutable principal pour les fichiers C++
add_executable(cuvista ${CPP_SOURCES})

# Lier la bibliothèque CUDA avec l'exécutable principal en utilisant la même signature
target_link_libraries(cuvista PRIVATE cuvista_cuda ${CUDA_LIBRARIES} cuda cudart)`

This part works, but when I start compiling with make, I get this error : 

`/home/abaldanza/Documents/cuvista/Matrix/Image2.hpp:22:10: fatal error: format: Aucun fichier ou dossier de ce nom
   22 | #include <format>
      |          ^~~~~~~~`
      
Testing on simplified code, it seems that it's nvcc that doesn't support the inclusion of <format> (g++ manages to compile it). Do you know how I can separate the compilation between the cpp and cuda code so that nvcc doesn't compile this part of the code? If not, isn't it possible to call an nvcc-compilable library instead?

**Comment by RainerMtb** [comment]
This is likely an issue with C++ versions. I generally used C++20. Try setting 20 for nvcc, even if the cuda code itself does not require such a high version. But you will very likely run into more issues as I believe there is more windows code even in the command line version.

I will certainly need more time to get this all running.

**Comment by abaldanz** [comment]
Indeed, I got stuck in a superposition of errors ahahah. It seems complicated to do this myself, the code is quite complex.

It's frustrating because your algorithm is really breathtaking and we really need a tool like this to make progress on our research topic. 

Do you have any idea when you'll be able to work on it? And by the way, are you planning to develop a cropping/adjustment tool for the edges?

**Comment by RainerMtb** [comment]
I really do not know when I get it running on linux, I first have to get used to linux.

**Comment by RainerMtb** [comment]
It now compiles and runs on Ubuntu 24.04 for me
You will need to apt-install the following libraries: `libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev libcpu-features-dev`
You should then get an executable `cuvista` in a subfolder `./cuvistaCli`

**Comment by RainerMtb** [comment]
For cropping/adjusting edges: Do you mean when an edge of the video becomes visible due to large movement of frames? You can set a higher `-zoom` parameter for avoiding that, default is 1.05

**Comment by abaldanz** [comment]
Thank you so much, I didn't expect you to go so fast! I'll test it today.

For the edge cropping I was actually talking about something adaptive. A way of adjusting this zoom factor according to the movement in the frames so as to minimize the loss of information. Or in the worst case, a way of thresholding the stabilization so that, if I set the zoom threshold to a value of z, no edge can be seen under any circumstances.
But now that the code is compilable on linux I'll be able to take a look at it.

Thank you again for this great work.

**Comment by RainerMtb** [comment]
Ok some dynamic zoom, I will have a look, but I really want to do some other things first

**Comment by abaldanz** [comment]
Thank you very much. Can't wait to see it.

**Comment by RainerMtb** [comment]
There now is a dynamic zoom feature in the repo, did not update the release for now.

There still are hard limits to the zoom, which are set by default to 5% and 25%, you set those via the option ```-zoom min:max``` where you now specify numbers in percent. So the default would be equal to ```-zoom 5:25```. You can still specify just one zoom value, which will be the old behaviour.

**Comment by abaldanz** [comment]
Thank you so much, it's amazing. I can't wait to try it. Congratulations for your work.
